development:
  secret_key_base: here_goes_my_secret_key_base
  google_client_id: 437260504023-b9mjbb6u8dh56ml29al88qc266u0oamn.apps.googleusercontent.com
  google_secret: o6vOZFyjJN6Gwp90PMUKct6j

test:
  secret_key_base: here_goes_my_secret_key_base

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_secret: <%= ENV["GOOGLE_SECRET"] %>
